### ISSUE TITLE
在使用release v0.2.1导出CC的SCX时遇到的问题

### ISSUE THREAD

**Issue by HimuL-Phsam** [wetor/MagesTools#1]
**导出文本**
如果当前scx脚本导出后的txt内容为空，程序会直接报错。如果是在批量导出时，必须要把这些空的scx取出，才能继续批量导出。
![image-20220709151115360](https://user-images.githubusercontent.com/83492969/178096620-5af763cf-b227-47bd-bad5-1bbc14498e1a.png)
在同时使用[sc3tools](https://github.com/CommitteeOfZero/sc3tools)导出scx后，发现内容为空的文件如下：
![image-20220709152428075](https://user-images.githubusercontent.com/83492969/178096657-8884ad1e-16ed-4dd4-95ac-4b3d1ec03780.png)
以上文件的原scx文件使用MagesTools导出时均会报错，其余非0的均可以正常导出。

**导出文件夹所有**
在按Example导出文件夹所有时，并在排除上述的空内容scx后，虽然程序没有报错，但是output指定的文件夹并有导出的内容。
![image-20220709153628484](https://user-images.githubusercontent.com/83492969/178096681-55a56d34-bd9c-4eea-a219-9e4965676804.png)
![image-20220709153648706](https://user-images.githubusercontent.com/83492969/178096689-83259079-7e62-46f8-bb76-8700fa9ea746.png)

**Comment by wetor** [comment]
如果你还没有解决此问题，你可以上传一份样本，我有时间会进行修复

**Comment by wetor** [comment]
长时间未反馈，关闭。未解决可重新发起issue
