### ISSUE TITLE
请教一下码表、字符集如何获取？

### ISSUE THREAD

**Issue by alanliu02** [wetor/MagesTools#3]
尝试解码C;C的scx文件，字符集只在链接中找到PC版对应的charset.utf8，解码PC版scx文件正常。但使用同一字符集解码switch版出现index out of range。推测使用不同的字符集。请教一下码表/字符集如何获取？

**Comment by wetor** [comment]
一般是通过OCR等技术识别字库图像(system包内)  

或许可以分析二进制可执行文件，或者逆向来取得(我自己没有成功过，都是OCR)   

一般每个游戏都需要单独的去OCR，虽然新游戏有大部分可复用字符，但还不是完全一致，无法确保通用性，这也是我没有提供charset的原因，可以自行去OCR制作

**Comment by alanliu02** [comment]
好的，感谢回答
