### ISSUE TITLE
不知道怎么使用翻译功能

### ISSUE THREAD

**Issue by XuNianChou** [wetor/MagesTools#4]
![image](https://github.com/wetor/MagesTools/assets/63174439/6f756bb8-3322-41b1-ba2d-42801fe0a861)
因为不了解go语言，我不知自己哪里操作错了。
我不理解，工程文件里面没有./data文件夹，我需要自己创建一个data文件夹吗？
MJPN.txt文件我也没找到。
因为自己是菜鸟，希望能给出解答。

**Comment by wetor** [comment]
1. 此工具仅有处理脚本的功能，不具备处理和分析字库的功能
2. MJPN.txt是从游戏字库中提取出的字符集（即system/font图像中包含空格所有字符的txt文件，无换行），即使是同一个引擎，游戏的不同字符集也不尽相同，所以无法提供通用工具，需要自行处理
3. 一个完整的汉化首先需要从分析或解析字库开始
4. 可直接下载releases使用，不需要从源码编译

**Comment by wetor** [comment]
长时间未反馈，关闭
