### ISSUE TITLE
解码部分scx文件会报错

### ISSUE THREAD

**Issue by Fluchw** [wetor/MagesTools#5]
我现在整理好字符集了,也成功导出了部分文本,但是现在的问题是有部分文本会遇到报错,并且批量解码的命令不起作用

能否抽空帮我解决一下这个问题,拜托你了🙏🙏🙏
会报错的文件放在err文件夹里了
链接：https://pan.baidu.com/s/1TeFdwhX6nnWuHo3qZLo3_Q 
提取码：ssss 

[SG.zip](https://github.com/user-attachments/files/15580953/SG.zip)

**Comment by Fluchw** [comment]
![Uploading e.png…]()

**Comment by Fluchw** [comment]
> 我现在整理好字符集了,也成功导出了部分文本,但是现在的问题是有部分文本会遇到报错,并且批量解码的命令不起作用
> 
> 能否抽空帮我解决一下这个问题，拜托你了 🙏🙏🙏 会报错的文件放在err文件夹里了 链接：https://pan.baidu.com/s/1TeFdwhX6nnWuHo3qZLo3_Q 提取码：ssss

![e](https://github.com/wetor/MagesTools/assets/68312531/51ba8ad5-6377-40eb-ab67-4cd71a8aa949)

**Comment by wetor** [comment]
[Uploading SG.zip…]()
上传样例到github

**Comment by wetor** [comment]
已修复 [release v0.2.3](https://github.com/wetor/MagesTools/releases/tag/v0.2.3)

**Comment by Fluchw** [comment]
> 已修复 [release v0.2.3](https://github.com/wetor/MagesTools/releases/tag/v0.2.3)

非常感谢:D

**Comment by spaceskynet** [comment]
正好上周解包PSV亚版CC时也遇到了这个问题，最后也加个return就解决问题
